String1 =input("")
print(String1)
print("First character of String is: ")
print(String1[0])
print("Last character of String is: ")
print("Reverse of the string")
print(String1[-1])
print("Reverse of the string")
print(String1[ ::-1])
gfg = "".join(reversed(String1))
print(gfg)
